# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manago', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp_class',
        ),
        migrations.RemoveField(
            model_name='client_data',
            name='username',
        ),
        migrations.RemoveField(
            model_name='developer_data',
            name='username',
        ),
        migrations.AlterField(
            model_name='admin_data',
            name='password',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='admin_data',
            name='username',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='client_data',
            name='email',
            field=models.EmailField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client_data',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='client_data',
            name='number',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='client_data',
            name='project_deadline',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='client_data',
            name='project_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='developer_data',
            name='email',
            field=models.EmailField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='developer_data',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='developer_data',
            name='number',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='developer_data',
            name='project_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='developer_data',
            name='role',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='developer_data',
            name='team_id',
            field=models.CharField(max_length=40),
        ),
    ]
