# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import manago.models


class Migration(migrations.Migration):

    dependencies = [
        ('manago', '0002_auto_20170228_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_update', models.CharField(max_length=600)),
                ('file_name', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to=manago.models.upload_to)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
