# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manago', '0003_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='dev_id',
            field=models.EmailField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='date_updated',
            field=models.DateTimeField(),
        ),
    ]
