# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manago', '0006_auto_20170314_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='head_text',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
