# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manago', '0007_attachment_head_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='dev_id',
            new_name='devid',
        ),
    ]
